import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://aprydldykaikaftxqpwq.supabase.co';
const serviceRoleKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcnlkbGR5a2Fpa2FmdHhxcHdxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDYxNTc0MywiZXhwIjoyMDkwMTkxNzQzfQ.NMQ100c2THzqYcORjR10I5HrtTOGPcjYEtHq5ya37Z8';

const supabase = createClient(supabaseUrl, serviceRoleKey);

const leads = [
  {
    nombre_adulto_mayor: 'Rosa Inés Martínez Vargas',
    edad: 82,
    sexo: 'femenino',
    nombre_contacto: 'Carlos Martínez',
    parentesco: 'hijo',
    telefono_principal: '3001234567',
    ciudad: 'Bogotá',
    zona_localidad: 'Chapinero',
    presupuesto_mensual: 3500000,
    presupuesto_rango: '3-4M',
    urgencia: 'inmediato',
    diagnosticos: 'Alzheimer avanzado, hipertensión',
    movilidad: 'silla_de_ruedas',
    deterioro_cognitivo: true,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    estado: 'lead_nuevo',
    como_nos_conocio: 'Google',
    observaciones: 'La señora se escapó dos veces esta semana. Urgente.',
  },
  {
    nombre_adulto_mayor: 'Guillermo Ospina Restrepo',
    edad: 78,
    sexo: 'masculino',
    nombre_contacto: 'Luisa Ospina',
    parentesco: 'hija',
    telefono_principal: '3112345678',
    ciudad: 'Bogotá',
    zona_localidad: 'Usaquén',
    presupuesto_mensual: 5000000,
    presupuesto_rango: '5M+',
    urgencia: 'alta',
    diagnosticos: 'EPOC, insuficiencia cardíaca',
    movilidad: 'camina_con_ayuda',
    deterioro_cognitivo: false,
    requiere_oxigeno: true,
    requiere_enfermeria: true,
    requiere_acompanamiento: false,
    estado: 'lead_calificado',
    como_nos_conocio: 'Referido médico',
    observaciones: 'Requiere oxígeno 16 horas al día.',
  },
  {
    nombre_adulto_mayor: 'Amparo Cifuentes de Gómez',
    edad: 75,
    sexo: 'femenino',
    nombre_contacto: 'Jorge Gómez',
    parentesco: 'esposo',
    telefono_principal: '3223456789',
    ciudad: 'Medellín',
    zona_localidad: 'El Poblado',
    presupuesto_mensual: 2800000,
    presupuesto_rango: '2-3M',
    urgencia: 'media',
    diagnosticos: 'Parkinson, diabetes tipo 2',
    movilidad: 'camina_con_ayuda',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    dieta_diabetica: true,
    estado: 'hogares_propuestos',
    como_nos_conocio: 'Facebook',
    observaciones: 'Busca hogar donde haya fisioterapia diaria.',
  },
  {
    nombre_adulto_mayor: 'Héctor Ramírez Londoño',
    edad: 84,
    sexo: 'masculino',
    nombre_contacto: 'Patricia Ramírez',
    parentesco: 'hija',
    telefono_principal: '3134567890',
    ciudad: 'Bogotá',
    zona_localidad: 'Suba',
    presupuesto_mensual: 1800000,
    presupuesto_rango: '1.5-2M',
    urgencia: 'baja',
    diagnosticos: 'Demencia vascular leve',
    movilidad: 'camina_solo',
    deterioro_cognitivo: true,
    requiere_oxigeno: false,
    requiere_enfermeria: false,
    requiere_acompanamiento: true,
    estado: 'visitas_programadas',
    como_nos_conocio: 'Instagram',
    observaciones: 'Visita programada para el 5 de abril en Hogar San José.',
  },
  {
    nombre_adulto_mayor: 'Beatriz Elena Suárez Pardo',
    edad: 79,
    sexo: 'femenino',
    nombre_contacto: 'Andrés Suárez',
    parentesco: 'hijo',
    telefono_principal: '3045678901',
    ciudad: 'Bogotá',
    zona_localidad: 'Teusaquillo',
    presupuesto_mensual: 4200000,
    presupuesto_rango: '4-5M',
    urgencia: 'alta',
    diagnosticos: 'ACV con hemiplejia derecha, hipertensión',
    movilidad: 'silla_de_ruedas',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    ayuda_para_bano: true,
    ayuda_para_comer: true,
    estado: 'en_decision_familiar',
    como_nos_conocio: 'Médico tratante',
    observaciones: 'Familia evaluando entre dos hogares. Decide esta semana.',
  },
  {
    nombre_adulto_mayor: 'Alberto José Peña Castillo',
    edad: 88,
    sexo: 'masculino',
    nombre_contacto: 'Mónica Peña',
    parentesco: 'hija',
    telefono_principal: '3156789012',
    ciudad: 'Cali',
    zona_localidad: 'Ciudad Jardín',
    presupuesto_mensual: 3000000,
    presupuesto_rango: '3-4M',
    urgencia: 'inmediato',
    diagnosticos: 'Fractura de cadera post-operatoria, diabetes',
    movilidad: 'silla_de_ruedas',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    ayuda_para_caminar: true,
    dieta_diabetica: true,
    estado: 'cierre_ganado',
    como_nos_conocio: 'WhatsApp',
    observaciones: 'Ingresó al Hogar Los Cedros el 15 de marzo.',
  },
  {
    nombre_adulto_mayor: 'María Consuelo Vargas Ríos',
    edad: 71,
    sexo: 'femenino',
    nombre_contacto: 'Felipe Vargas',
    parentesco: 'hijo',
    telefono_principal: '3067890123',
    ciudad: 'Bogotá',
    zona_localidad: 'Kennedy',
    presupuesto_mensual: 1200000,
    presupuesto_rango: 'menos-1.5M',
    urgencia: 'baja',
    diagnosticos: 'Depresión mayor, artritis',
    movilidad: 'camina_solo',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: false,
    requiere_acompanamiento: true,
    estado: 'cierre_perdido',
    como_nos_conocio: 'Google',
    observaciones: 'Presupuesto insuficiente para los hogares disponibles. Decidió cuidado en casa.',
  },
  {
    nombre_adulto_mayor: 'Luis Ernesto Herrera Molina',
    edad: 80,
    sexo: 'masculino',
    nombre_contacto: 'Sandra Herrera',
    parentesco: 'hija',
    telefono_principal: '3178901234',
    ciudad: 'Bogotá',
    zona_localidad: 'Barrios Unidos',
    presupuesto_mensual: 2500000,
    presupuesto_rango: '2-3M',
    urgencia: 'media',
    diagnosticos: 'Insuficiencia renal crónica, hipertensión',
    movilidad: 'camina_con_ayuda',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: false,
    dieta_blanda: true,
    estado: 'lead_nuevo',
    como_nos_conocio: 'Clínica Shaio',
    observaciones: 'Viene de alta hospitalaria. Necesita dieta renal.',
  },
  {
    nombre_adulto_mayor: 'Carmen Lucía Torres Aguilar',
    edad: 77,
    sexo: 'femenino',
    nombre_contacto: 'Ricardo Torres',
    parentesco: 'hijo',
    telefono_principal: '3089012345',
    ciudad: 'Bogotá',
    zona_localidad: 'Fontibón',
    presupuesto_mensual: 3800000,
    presupuesto_rango: '3-4M',
    urgencia: 'alta',
    diagnosticos: 'Alzheimer moderado, incontinencia',
    movilidad: 'camina_solo',
    deterioro_cognitivo: true,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    ayuda_para_bano: true,
    estado: 'lead_calificado',
    como_nos_conocio: 'Recomendación familiar',
    observaciones: 'Cuidadora actual renunció. Urgente en 2 semanas.',
  },
  {
    nombre_adulto_mayor: 'Ernesto Bohórquez Fajardo',
    edad: 85,
    sexo: 'masculino',
    nombre_contacto: 'Diana Bohórquez',
    parentesco: 'hija',
    telefono_principal: '3190123456',
    ciudad: 'Bogotá',
    zona_localidad: 'Chapinero',
    presupuesto_mensual: 6000000,
    presupuesto_rango: '5M+',
    urgencia: 'media',
    diagnosticos: 'Parkinson avanzado, disfagia',
    movilidad: 'silla_de_ruedas',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    ayuda_para_comer: true,
    dieta_blanda: true,
    estado: 'hogares_propuestos',
    como_nos_conocio: 'Neurólogo tratante',
    observaciones: 'Requiere fonoaudiología por disfagia. Presupuesto alto, exige calidad.',
  },
  {
    nombre_adulto_mayor: 'Gloria Esperanza Morales Vega',
    edad: 73,
    sexo: 'femenino',
    nombre_contacto: 'Juan Pablo Morales',
    parentesco: 'hijo',
    telefono_principal: '3201234567',
    ciudad: 'Bogotá',
    zona_localidad: 'Engativá',
    presupuesto_mensual: 2000000,
    presupuesto_rango: '2-3M',
    urgencia: 'baja',
    diagnosticos: 'Osteoporosis, depresión leve',
    movilidad: 'camina_con_ayuda',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: false,
    requiere_acompanamiento: true,
    estado: 'visitas_programadas',
    como_nos_conocio: 'Facebook',
    observaciones: 'Prefiere hogar con actividades recreativas y jardín.',
  },
  {
    nombre_adulto_mayor: 'Rodrigo Augusto Cárdenas Núñez',
    edad: 81,
    sexo: 'masculino',
    nombre_contacto: 'Valentina Cárdenas',
    parentesco: 'nieta',
    telefono_principal: '3112345670',
    ciudad: 'Bogotá',
    zona_localidad: 'Usaquén',
    presupuesto_mensual: 4500000,
    presupuesto_rango: '4-5M',
    urgencia: 'alta',
    diagnosticos: 'Cardiopatía isquémica, EPOC leve',
    movilidad: 'camina_solo',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: false,
    estado: 'en_decision_familiar',
    como_nos_conocio: 'Google',
    observaciones: 'Junta médica recomienda hogar. Familia en debate.',
  },
  {
    nombre_adulto_mayor: 'Cecilia del Carmen Jiménez Polo',
    edad: 86,
    sexo: 'femenino',
    nombre_contacto: 'Hernán Jiménez',
    parentesco: 'hijo',
    telefono_principal: '3023456780',
    ciudad: 'Barranquilla',
    zona_localidad: 'El Prado',
    presupuesto_mensual: 2200000,
    presupuesto_rango: '2-3M',
    urgencia: 'inmediato',
    diagnosticos: 'Demencia senil, riesgo de caídas alto',
    movilidad: 'silla_de_ruedas',
    deterioro_cognitivo: true,
    requiere_oxigeno: false,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    requiere_primer_piso: true,
    estado: 'lead_nuevo',
    como_nos_conocio: 'WhatsApp',
    observaciones: 'Tuvo caída grave la semana pasada. Necesita primer piso obligatorio.',
  },
  {
    nombre_adulto_mayor: 'Jaime Iván Muñoz Acosta',
    edad: 76,
    sexo: 'masculino',
    nombre_contacto: 'Claudia Muñoz',
    parentesco: 'hija',
    telefono_principal: '3145678900',
    ciudad: 'Bogotá',
    zona_localidad: 'Bosa',
    presupuesto_mensual: 1600000,
    presupuesto_rango: '1.5-2M',
    urgencia: 'media',
    diagnosticos: 'Diabetes tipo 2, hipertensión, artritis',
    movilidad: 'camina_solo',
    deterioro_cognitivo: false,
    requiere_oxigeno: false,
    requiere_enfermeria: false,
    requiere_acompanamiento: true,
    dieta_diabetica: true,
    estado: 'lead_calificado',
    como_nos_conocio: 'Instagram',
    observaciones: 'Busca hogar económico pero con buena alimentación.',
  },
  {
    nombre_adulto_mayor: 'Nohora Inés Pedraza Salcedo',
    edad: 90,
    sexo: 'femenino',
    nombre_contacto: 'Mauricio Pedraza',
    parentesco: 'hijo',
    telefono_principal: '3056789010',
    ciudad: 'Bogotá',
    zona_localidad: 'Teusaquillo',
    presupuesto_mensual: 7000000,
    presupuesto_rango: '5M+',
    urgencia: 'alta',
    diagnosticos: 'Alzheimer severo, incontinencia, úlceras por presión',
    movilidad: 'postrado',
    deterioro_cognitivo: true,
    requiere_oxigeno: true,
    requiere_enfermeria: true,
    requiere_acompanamiento: true,
    ayuda_para_comer: true,
    ayuda_para_bano: true,
    dieta_blanda: true,
    estado: 'hogares_propuestos',
    como_nos_conocio: 'Médico geriatra',
    observaciones: 'Caso muy complejo. Requiere hogar especializado con enfermería 24h y manejo de O2.',
  },
];

const hogares = [
  {
    nombre: 'Hogar San Rafael',
    direccion: 'Calle 72 # 11-45',
    localidad: 'Teusaquillo',
    zona: 'Centro-Occidente',
    ciudad: 'Bogotá',
    telefono: '6012345678',
    whatsapp: '3101234560',
    habitaciones_disponibles: 3,
    cupo_disponible: 3,
    precio_desde: 2500000,
    precio_hasta: 4500000,
    hab_compartida: true,
    hab_privada_bano_privado: true,
    hab_privada_bano_compartido: true,
    serv_enfermeria_24h: true,
    serv_fisioterapia: true,
    serv_terapia_ocupacional: true,
    serv_psicologia: false,
    serv_nutricion: true,
    serv_actividades_recreativas: true,
    serv_medicina_general: true,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: true,
    maneja_demencia: true,
    maneja_silla_ruedas: true,
    tiene_ascensor: false,
    un_solo_nivel: true,
    descripcion: 'Hogar especializado en adultos con deterioro cognitivo. Personal capacitado 24/7. Jardín interior y zona de terapias.',
    estado: 'aprobado',
  },
  {
    nombre: 'Residencia Los Nogales',
    direccion: 'Carrera 15 # 88-32',
    localidad: 'Usaquén',
    zona: 'Norte',
    ciudad: 'Bogotá',
    telefono: '6019876543',
    whatsapp: '3209876540',
    habitaciones_disponibles: 5,
    cupo_disponible: 5,
    precio_desde: 4000000,
    precio_hasta: 8000000,
    hab_compartida: false,
    hab_privada_bano_privado: true,
    hab_privada_bano_compartido: false,
    serv_enfermeria_24h: true,
    serv_fisioterapia: true,
    serv_terapia_ocupacional: true,
    serv_psicologia: true,
    serv_nutricion: true,
    serv_actividades_recreativas: true,
    serv_medicina_general: true,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: true,
    maneja_demencia: true,
    maneja_silla_ruedas: true,
    tiene_ascensor: true,
    un_solo_nivel: false,
    descripcion: 'Hogar de alto estándar con médico residente. Habitaciones privadas baño privado. Jardín, zona verde y sala de terapias completa.',
    estado: 'aprobado',
  },
  {
    nombre: 'Casa del Abuelo Feliz',
    direccion: 'Calle 134 # 52-18',
    localidad: 'Suba',
    zona: 'Norte',
    ciudad: 'Bogotá',
    telefono: '6013456789',
    whatsapp: '3153456780',
    habitaciones_disponibles: 2,
    cupo_disponible: 2,
    precio_desde: 1800000,
    precio_hasta: 3000000,
    hab_compartida: true,
    hab_privada_bano_privado: false,
    hab_privada_bano_compartido: true,
    serv_enfermeria_24h: false,
    serv_fisioterapia: true,
    serv_terapia_ocupacional: false,
    serv_psicologia: false,
    serv_nutricion: false,
    serv_actividades_recreativas: true,
    serv_medicina_general: false,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: false,
    maneja_demencia: false,
    maneja_silla_ruedas: false,
    tiene_ascensor: false,
    un_solo_nivel: true,
    descripcion: 'Hogar familiar y cálido para adultos mayores independientes. Jardín con huerta terapéutica. Actividades recreativas diarias.',
    estado: 'aprobado',
  },
  {
    nombre: 'Fundación Gerontos',
    direccion: 'Avenida 68 # 23-55',
    localidad: 'Puente Aranda',
    zona: 'Centro-Occidente',
    ciudad: 'Bogotá',
    telefono: '6014567890',
    whatsapp: '3164567890',
    habitaciones_disponibles: 7,
    cupo_disponible: 7,
    precio_desde: 2800000,
    precio_hasta: 5500000,
    hab_compartida: true,
    hab_privada_bano_privado: true,
    hab_privada_bano_compartido: true,
    serv_enfermeria_24h: true,
    serv_fisioterapia: true,
    serv_terapia_ocupacional: true,
    serv_psicologia: true,
    serv_nutricion: true,
    serv_actividades_recreativas: true,
    serv_medicina_general: true,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: true,
    maneja_demencia: true,
    maneja_silla_ruedas: true,
    tiene_ascensor: true,
    un_solo_nivel: false,
    descripcion: 'Institución con 20 años de experiencia. Especialistas en pacientes complejos con múltiples patologías crónicas.',
    estado: 'aprobado',
  },
  {
    nombre: 'Hogar Doña Luz',
    direccion: 'Calle 57 # 24-10',
    localidad: 'Chapinero',
    zona: 'Centro-Oriente',
    ciudad: 'Bogotá',
    telefono: '6015678901',
    whatsapp: '3175678901',
    habitaciones_disponibles: 1,
    cupo_disponible: 1,
    precio_desde: 2000000,
    precio_hasta: 3500000,
    hab_compartida: true,
    hab_privada_bano_privado: false,
    hab_privada_bano_compartido: true,
    serv_enfermeria_24h: false,
    serv_fisioterapia: false,
    serv_terapia_ocupacional: false,
    serv_psicologia: false,
    serv_nutricion: false,
    serv_actividades_recreativas: true,
    serv_medicina_general: false,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: false,
    maneja_demencia: false,
    maneja_silla_ruedas: false,
    tiene_ascensor: false,
    un_solo_nivel: false,
    descripcion: 'Hogar pequeño y acogedor. Atención personalizada. Solo para adultos con movilidad reducida pero no postrados.',
    estado: 'aprobado',
  },
  {
    nombre: 'Clínica Geriátrica Santa Lucía',
    direccion: 'Carrera 11 # 93-52',
    localidad: 'Usaquén',
    zona: 'Norte',
    ciudad: 'Bogotá',
    telefono: '6016789012',
    whatsapp: '3186789012',
    habitaciones_disponibles: 8,
    cupo_disponible: 8,
    precio_desde: 5000000,
    precio_hasta: 12000000,
    hab_compartida: false,
    hab_privada_bano_privado: true,
    hab_privada_bano_compartido: false,
    serv_enfermeria_24h: true,
    serv_fisioterapia: true,
    serv_terapia_ocupacional: true,
    serv_psicologia: true,
    serv_nutricion: true,
    serv_actividades_recreativas: true,
    serv_medicina_general: true,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: true,
    maneja_demencia: true,
    maneja_silla_ruedas: true,
    tiene_ascensor: true,
    un_solo_nivel: false,
    descripcion: 'Institución de nivel clínico. Ideal para casos de alta complejidad médica. UCI geriátrica disponible. Médico geriatra residente.',
    estado: 'aprobado',
  },
  {
    nombre: 'Hogar La Esperanza de Engativá',
    direccion: 'Calle 68 # 77-25',
    localidad: 'Engativá',
    zona: 'Occidente',
    ciudad: 'Bogotá',
    telefono: '6017890123',
    whatsapp: '3197890123',
    habitaciones_disponibles: 4,
    cupo_disponible: 4,
    precio_desde: 1500000,
    precio_hasta: 2500000,
    hab_compartida: true,
    hab_privada_bano_privado: false,
    hab_privada_bano_compartido: true,
    serv_enfermeria_24h: true,
    serv_fisioterapia: false,
    serv_terapia_ocupacional: false,
    serv_psicologia: false,
    serv_nutricion: false,
    serv_actividades_recreativas: true,
    serv_medicina_general: true,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: false,
    maneja_demencia: false,
    maneja_silla_ruedas: true,
    tiene_ascensor: false,
    un_solo_nivel: true,
    descripcion: 'Opción económica con buena atención básica. Un solo nivel sin escaleras. Muy bien recomendado por familias del occidente de Bogotá.',
    estado: 'aprobado',
  },
  {
    nombre: 'Residencia Villa del Río',
    direccion: 'Calle 13 Sur # 40-15',
    localidad: 'Antonio Nariño',
    zona: 'Centro-Sur',
    ciudad: 'Bogotá',
    telefono: '6018901234',
    whatsapp: '3108901234',
    habitaciones_disponibles: 6,
    cupo_disponible: 6,
    precio_desde: 2000000,
    precio_hasta: 4000000,
    hab_compartida: true,
    hab_privada_bano_privado: true,
    hab_privada_bano_compartido: false,
    serv_enfermeria_24h: true,
    serv_fisioterapia: true,
    serv_terapia_ocupacional: false,
    serv_psicologia: false,
    serv_nutricion: true,
    serv_actividades_recreativas: true,
    serv_medicina_general: true,
    dieta_blanda: true,
    dieta_diabetica: true,
    maneja_oxigeno: true,
    maneja_demencia: false,
    maneja_silla_ruedas: true,
    tiene_ascensor: false,
    un_solo_nivel: true,
    descripcion: 'Hogar de tamaño mediano con buena relación calidad-precio. Especializado en adultos con movilidad reducida y post-quirúrgicos.',
    estado: 'aprobado',
  },
];

async function seed() {
  console.log('🌱 Iniciando seeding de base de datos...\n');

  // Insert leads
  console.log('📋 Insertando 15 leads...');
  const { data: leadsData, error: leadsError } = await supabase
    .from('leads')
    .insert(leads)
    .select('id, nombre_adulto_mayor, estado, urgencia');

  if (leadsError) {
    console.error('❌ Error insertando leads:', leadsError.message);
    process.exit(1);
  }

  console.log(`✅ ${leadsData.length} leads insertados:`);
  leadsData.forEach(l => console.log(`   - ${l.nombre_adulto_mayor} | ${l.estado} | urgencia: ${l.urgencia}`));

  // Insert hogares
  console.log('\n🏠 Insertando 8 hogares...');
  const { data: hogaresData, error: hogaresError } = await supabase
    .from('hogares')
    .insert(hogares)
    .select('id, nombre, localidad, precio_desde, precio_hasta');

  if (hogaresError) {
    console.error('❌ Error insertando hogares:', hogaresError.message);
    process.exit(1);
  }

  console.log(`✅ ${hogaresData.length} hogares insertados:`);
  hogaresData.forEach(h => console.log(`   - ${h.nombre} | ${h.localidad} | $${h.precio_desde?.toLocaleString()} - $${h.precio_hasta?.toLocaleString()}`));

  console.log('\n🎉 Seeding completado exitosamente!');
}

seed().catch(console.error);
